name: Booking bdd tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run smoke tests
        run: behave --no-capture --tags=smoke

  regression:
    runs-on: ubuntu-latest
    needs: smoke
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run regression tests with Allure
        run: |
          behave --no-capture --tags=regression \
          -f allure_behave.formatter:AllureFormatter \
          -o allure-results

      - name: Generate Allure Report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report